import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/react-query/QueryProvider";
import { ContextProvider } from "@/context/Context";
import { lazy } from "react";

const Header = lazy(() => import("@/components/header/Header"))
const Footer = lazy(() => import("@/components/footer/Footer"))

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Green Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ContextProvider>
            <Header />
            {children}
            <Footer/>
          </ContextProvider>
        </Providers>
      </body>
    </html>
  );
}
